spring.application.name=api-imobiliaria

spring.datasource.url=jdbc:mysql://localhost:3306/db_imobiliaria
spring.datasource.username=root
spring.datasource.password=Isak@mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



